### ISSUE TITLE
prismaを使って、データベースのテーブルを作成する

### ISSUE THREAD

**Issue by AyumuOgasawara** [AyumuOgasawara/receipt-scanner#25]
## 概要
[prisma](https://www.prisma.io/)を使用して、データベースのテーブルを作成する。

**Comment by AyumuOgasawara** [comment]
## 認証がうまくできない

compose.ymlの設定
``` yml
db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: receiptScanner
    ports:
      - 5432:5432
```

.env
``` .env
DATABASE_URL="postgresql://postgres:receiptScanner@localhost:5432/mydb?schema=public"
```

schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
